#!/usr/bin/env bash
# ==============================================================================
# Thunderdome Demon Template
# ==============================================================================
# 
# Copy this template to create new demons.
# All demons must:
#   1. Accept --repo <path> argument
#   2. Write reports to $TARGET_REPO/tests/REPORTS/current/
#   3. Use standardized report naming via common.sh helpers
#   4. Exit 0 on success, non-zero on P0 issues found
#
# ==============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
THUNDERDOME_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Source common library
source "$THUNDERDOME_ROOT/lib/common.sh"

# ==============================================================================
# Configuration
# ==============================================================================

DEMON_NAME="template"  # Change this!
DEMON_SCOPE="scan"     # e.g., "security", "gap", "mcp", etc.

# ==============================================================================
# Argument Parsing
# ==============================================================================

TARGET_REPO=""

while [[ $# -gt 0 ]]; do
    case $1 in
        --repo)
            shift
            TARGET_REPO="${1:-}"
            ;;
        --help|-h)
            echo "Usage: $(basename "$0") --repo <path>"
            exit 0
            ;;
        *)
            err "Unknown option: $1"
            exit 1
            ;;
    esac
    shift
done

# Resolve target repo
TARGET_REPO=$(resolve_target_repo "$TARGET_REPO")

if [[ ! -d "$TARGET_REPO" ]]; then
    err "Target repository does not exist: $TARGET_REPO"
    exit 1
fi

# ==============================================================================
# Main Logic
# ==============================================================================

log_header "$DEMON_NAME Demon"
log_info "Target: $TARGET_REPO"
repo_snapshot "$TARGET_REPO"

# Initialize report
REPORT_FILE=$(report_path "$TARGET_REPO" "$DEMON_NAME" "$DEMON_SCOPE")
log_info "Report: $REPORT_FILE"

# TODO: Implement your demon logic here
# - Run checks
# - Collect findings
# - Write structured report to $REPORT_FILE

cat > "$REPORT_FILE" <<EOF
# ${DEMON_NAME^} Report - $(date +%Y-%m-%d)

**Generated:** $(date +%H:%M:%S)
**Repository:** $TARGET_REPO

## Summary

This is a template report. Implement your demon logic!

## Findings

None (template)

---

*Report generated by $DEMON_NAME demon.*
EOF

log_success "Report written to: $REPORT_FILE"
