#!/usr/bin/env python3
"""
Stub docgen script for testing and development.

This script accepts JSON input via stdin and outputs either NO-OP or
generated documentation with SHA256 header.
"""

import json
import sys


def main():
    # Read JSON from stdin
    input_json = sys.stdin.read()
    data = json.loads(input_json)
    
    # Extract fields
    repo_root = data.get("repo_root")
    relative_path = data.get("relative_path")
    file_sha256 = data.get("file_sha256")
    source_contents = data.get("source_contents", "")
    existing_doc = data.get("existing_doc_contents")
    graph_context = data.get("graph_context")
    
    # Generate simple documentation
    doc_lines = []
    doc_lines.append(f"SHA256: {file_sha256}")
    doc_lines.append("")
    doc_lines.append(f"# Documentation for `{relative_path}`")
    doc_lines.append("")
    doc_lines.append("## Overview")
    doc_lines.append("")
    doc_lines.append(f"This is auto-generated documentation for `{relative_path}`.")
    doc_lines.append("")
    
    # Add source sample
    lines = source_contents.split("\n")
    if lines:
        doc_lines.append("## Source Preview")
        doc_lines.append("")
        doc_lines.append("```")
        for i, line in enumerate(lines[:10], 1):
            doc_lines.append(line)
        if len(lines) > 10:
            doc_lines.append("...")
        doc_lines.append("```")
        doc_lines.append("")
    
    # Add graph context if available
    if graph_context and "no_graph_data" not in graph_context:
        doc_lines.append("## Graph Context")
        doc_lines.append("")
        doc_lines.append("```")
        doc_lines.append(graph_context)
        doc_lines.append("```")
        doc_lines.append("")
    
    doc_lines.append(f"**Generated by:** docgen_stub.py")
    doc_lines.append(f"**Repository:** {repo_root}")
    
    # Output documentation
    print("\n".join(doc_lines))


if __name__ == "__main__":
    main()
